spring:
  application:
    name: employee-service

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082

employee-management-service:
  version: 1.0.0